version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 15s
      retries: 5
    networks:
      - network

  worker:
    build: .
    environment:
      WS_POOL_SIZE: ${WS_POOL_SIZE:-20000}
      MSG_COUNT: ${MSG_COUNT:-1000}
      MSG_DELAY: ${MSG_DELAY:-30}
      WS_ADDR: ${WS_ADDR:-ws://host.docker.internal:8080/}
      AMQP_ADDR: ${AMQP_ADDR:-amqp://guest:guest@rabbitmq:5672/%2f}
      RUST_LOG: ${RUST_LOG:-info}
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - network

networks:
  network: {}
